name: Deploy to Server

on:
    push:
        branches:
            - stable

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  extensions: mysqli, pdo_mysql
                  coverage: none

            - name: Install dependencies
              run: composer install --no-dev --optimize-autoloader

            - name: Install SSHpass
              run: sudo apt-get install -y sshpass

            - name: Deploy
              env:
                  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
              run: |
                  # Accept SSH host key
                  mkdir -p ~/.ssh
                  ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

                  # Create airclass-api directory if it doesn't exist
                  sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p ${{ secrets.DEPLOY_PATH }}/airclass-api"

                  # Upload files to server
                  sshpass -p "$SERVER_PASSWORD" rsync -avz --delete \
                    -e "ssh -o StrictHostKeyChecking=no" \
                    --exclude '.git' \
                    --exclude '.github' \
                    --exclude '.env' \
                    --exclude '.env.example' \
                    --exclude 'README.md' \
                    ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}/airclass-api/

                  # Set permissions, configure Apache, and restart services
                  sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "\
                    cd ${{ secrets.DEPLOY_PATH }}/airclass-api && \
                    # Set file permissions
                    sudo -S chown -R www-data:www-data . <<< '$SERVER_PASSWORD' && \
                    sudo -S chmod -R 755 . <<< '$SERVER_PASSWORD' && \
                    sudo -S chmod -R 775 uploads logs <<< '$SERVER_PASSWORD' && \
                    # Ensure .htaccess exists and has correct permissions
                    sudo -S chmod 644 .htaccess <<< '$SERVER_PASSWORD' && \
                    # Enable mod_rewrite if not already enabled
                    sudo -S a2enmod rewrite <<< '$SERVER_PASSWORD' && \
                    # Create Apache virtual host config if it doesn't exist
                    echo '<VirtualHost *:80>
                        ServerAdmin webmaster@localhost
                        DocumentRoot ${{ secrets.DEPLOY_PATH }}/airclass-api
                        <Directory ${{ secrets.DEPLOY_PATH }}/airclass-api>
                            Options Indexes FollowSymLinks
                            AllowOverride All
                            Require all granted
                        </Directory>
                        ErrorLog \${APACHE_LOG_DIR}/airclass-api-error.log
                        CustomLog \${APACHE_LOG_DIR}/airclass-api-access.log combined
                    </VirtualHost>' | sudo -S tee /etc/apache2/sites-available/airclass-api.conf <<< '$SERVER_PASSWORD' && \
                    # Enable the site if not already enabled
                    sudo -S a2ensite airclass-api.conf <<< '$SERVER_PASSWORD' && \
                    # Restart services
                    sudo -S systemctl restart apache2 <<< '$SERVER_PASSWORD' && \
                    sudo -S systemctl restart php8.2-fpm <<< '$SERVER_PASSWORD'"
