name: Deploy to Server

on:
    push:
        branches:
            - stable

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install SSHpass
              run: sudo apt-get install -y sshpass

            - name: Deploy
              env:
                  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
              run: |
                  # Accept SSH host key
                  mkdir -p ~/.ssh
                  ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

                  # Upload files to server
                  sshpass -p "$SERVER_PASSWORD" rsync -avz --delete \
                    -e "ssh -o StrictHostKeyChecking=no" \
                    --exclude '.git' \
                    --exclude '.github' \
                    --exclude '.env' \
                    --exclude '.env.example' \
                    --exclude 'README.md' \
                    ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}/

                  # Set permissions and restart PHP
                  sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "\
                    cd ${{ secrets.DEPLOY_PATH }} && \
                    sudo -S chown -R www-data:www-data . <<< '$SERVER_PASSWORD' && \
                    sudo -S chmod -R 755 . <<< '$SERVER_PASSWORD' && \
                    sudo -S chmod -R 775 uploads logs <<< '$SERVER_PASSWORD' && \
                    sudo -S systemctl restart php8.2-fpm <<< '$SERVER_PASSWORD'"
